G1=/mnt/disco_d/meus_documentos/configurar_pc/pc/manual/correcoes/heroic/scripts/restore_elden_ring.sh
G2=
G3=
G4=
G5=
G6=/mnt/disco_d/meus_documentos/configurar_pc/pc/manual/correcoes/heroic/scripts/backup_elden_ring.sh
